application: scoopstream
version: 1-00
runtime: python
api_version: 1

handlers:

- url: /static/
  static_dir: static/


- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  
- url: /console/static
  static_dir: console/app/view/static  
  
- url: /console.*
  script: console/app/console.py
  login: admin

    
- url: .*
  script: main.py


